# Generated by Django 2.2.3 on 2020-10-08 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='id',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
