# Generated by Django 2.2.3 on 2020-10-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_auto_20201008_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='_id',
            new_name='ab_id',
        ),
    ]
