# Generated by Django 2.2.3 on 2020-10-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0004_auto_20201009_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='geocode_generated',
            field=models.BooleanField(default=False),
        ),
    ]
