# Generated by Django 2.2.3 on 2020-10-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0005_addressbook_geocode_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='excel_file',
            field=models.FileField(upload_to='uploaded_add_books/excel/'),
        ),
    ]
